_BASE_: Base-Cell-InstanceSegmentation.yaml
MODEL:
  META_ARCHITECTURE: "CtDINO"
  SEM_SEG_HEAD:
    NAME: "CtDINOHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 2
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MaskDINOEncoder"
    DIM_FEEDFORWARD: 1024
    NUM_FEATURE_LEVELS: 3
    TOTAL_NUM_FEATURE_LEVELS: 3
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
    WITH_POSITION: False
    NMS_QUERY_SELECT: True
    FEATURE_AUG: True
  MaskDINO:
    TRANSFORMER_DECODER_NAME: "CtDINODecoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 4.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    BOX_WEIGHT: 5.0
    GIOU_WEIGHT: 2.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 180
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 9  # 9+1, 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 10000
    TRAIN_GT_POINTS: 5000
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    INITIAL_PRED: True
    TWO_STAGE: True
    DN: "ct"
    DN_NUM: 100
    INITIALIZE_BOX_TYPE: "bitmask"   #"bitmask"
    OBOX_LOSS: True
    BOX_LOSS: False
    DUPLICATE_BOX_MATCHING: False
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.25

DATASETS:
  TRAIN: ("live_cell_train",)
INPUT:
  IMAGE_SIZE: 512
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1024
  DATASET_MAPPER_NAME: "live_cell_instance_detr"
  LIVE_CELL: True
SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 4
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 500000
  DETECTIONS_PER_IMAGE: 100
#  EVAL_FLAG: 1


OUTPUT_DIR: "output/train_live_cell"